### ISSUE TITLE
Implement Ingress Controller

### ISSUE THREAD

**Issue by renuka-fernando** [renuka-fernando/k8s-api-operator#1]
### Description
This is to track the tasks related to ingress controller implementation.

### Tasks

Design
- [x] Identify TLS configuration scenarios and how to configure them in envoy
- [x] Define annotations

Implementation 
- [ ] Configure APICTL project with TLS configurations
- [ ] Configure APICTL project with path routes
- [ ] Unit tests for scenarios.
- [ ] Document scenarios with examples
- [ ] Deploy ingress in cloud platforms and local deployments
